language: c
sudo: required
services:
- docker
script:
- make -f Makefile.docker docker-build
notifications:
  slack:
    secure: gDQXXz9C5FPFzXJG/5Zpy1AHk0kWvLfkOJSdwTaGrU6jA5zZmcJU46z8pG/ch7qZmTKvtuthdfI5gWd3U8ZFs1KPn3iQwk7LgQgEq3TTBaa+L3DPK9ChD5JnOGiYbTOUYnhwlMRnD/0XxK4gZbJ1aiw2EZmjQRYqYsrKPEYNy3ZGDH9ipHCpBz+83HhlbSOpSq2eeKSjs6+qKeSQZCR7l9u31lWGHWrrzqaDS0/z9Fz0amQXw2bc5me2R1891H6lTZhO1sysVXgXcMfqB2lHetJYyhdbRfLDhpXQD2XvvBbpD139ae40M+1GsnAPMSHnu0vho0I6GTj1lCfomPj2cjzON9hilijMTkDb3DSwwxaB9GORwdH0Y7Cqvj8laihOVC0sCCLUGgEKNPOypB5pNM5h6fnbHsv37iKXhwl7ls76Xf+Fz87v8NnOE4/wPFUga7his6OhtaLJZcDs/s5PAmy8kDQ2WwTlNfX1kqTndHBwzunhW2rrA0IXHujlxS4CCWoKrK5vge0O7jqLvjdMQeP5F1Q8PfTl5mRfu+pgbuOOf66qaGSLM+L43tMOFdq7q0hVi522KRFn30u+521M42szzElfk2uBE4qJwLL8Cz0ByhpoCaZzWYSwJ8R0TVsyknYdHbb96CCreVTcCb9ZJRC+sARJVajA779TJ/6Az6A=
