# vim:set sw=2 ts=2 et

apiVersion: v1
kind: Service
metadata:
  name: trafficserver
  namespace: kube-system
spec:
  selector:
    app: trafficserver
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30080
    targetPort: http
  - name: https
    protocol: TCP
    port: 443
    nodePort: 30443
    targetPort: https

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trafficserver
  namespace: kube-system
  labels:
    app: trafficserver
spec:
  replicas: 2

  selector:
    matchLabels:
      app: trafficserver

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      namespace: kube-system
      labels:
        app: trafficserver

    spec:

      volumes:
      - name: ts-storage
        emptyDir: {}

      containers:
      - name: trafficserver

        image: docker.io/torchbox/trafficserver-ingress-controller:latest
        imagePullPolicy: Always

        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
        - name: https
          protocol: TCP
          containerPort: 8443

        volumeMounts:
        - name: ts-storage
          mountPath: /var/lib/trafficserver

        resources:
          limits:
            cpu: "1"
            memory: 196Mi
          requests:
            cpu: 100m
            memory: 128Mi

        livenessProbe:
          httpGet:
            path: /__trafficserver_alive
            port: http
            httpHeaders:
            - name: Host
              value: localhost
          initialDelaySeconds: 3
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          periodSeconds: 3

        readinessProbe:
          httpGet:
            path: /__trafficserver_alive
            port: http
            httpHeaders:
            - name: Host
              value: localhost
          initialDelaySeconds: 3
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          periodSeconds: 3
